/**
 * TODO: Replace null prices with confirmed restaurant pricing before enabling real payment checkout.
 */
import type { MenuItem } from "./schema";

export const localMenuItems: MenuItem[] = [
  {
    id: "burger-loca",
    active: true,
    category: "Hamburguesas",
    sortOrder: 1,
    name: "Loca",
    description:
      "Ham patty, ham, white cheese, bacon, mayo, ketchup, mustard, lettuce, tomato, avocado.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "burger-regia",
    active: true,
    category: "Hamburguesas",
    sortOrder: 2,
    name: "Regia",
    description:
      "Ham patty, ham, white cheese, bacon, salami, mayo, ketchup, mustard, lettuce, tomato, avocado.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "burger-hawaiana",
    active: true,
    category: "Hamburguesas",
    sortOrder: 3,
    name: "Hawaiana",
    description:
      "Ham patty, ham, white cheese, tomato, Canadian bacon, pineapple, grilled onion, lettuce.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-nortena",
    active: true,
    category: "Hamburguesas",
    sortOrder: 4,
    name: "Norteña",
    description:
      "Ham patty, ham, white cheese, bacon, smoked grilled sausage, lettuce, tomato, avocado.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-cheeseburger",
    active: true,
    category: "Hamburguesas",
    sortOrder: 5,
    name: "Cheeseburger",
    description: "Ham patty, ham, cheddar cheese, mayo, ketchup, mustard, lettuce, tomato.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-mushroom",
    active: true,
    category: "Hamburguesas",
    sortOrder: 6,
    name: "Mushroom",
    description:
      "Ham patty, mushrooms, grilled onion, mayo, ketchup, mustard, lettuce, tomato.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-bacon-cheeseburger",
    active: true,
    category: "Hamburguesas",
    sortOrder: 7,
    name: "Bacon Cheeseburger",
    description: "Cheeseburger with bacon.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-bbq",
    active: true,
    category: "Hamburguesas",
    sortOrder: 8,
    name: "BBQ Burger",
    description: "Shredded pork in BBQ sauce, white cheese, onion rings, mayo.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "burger-chicken-sandwich",
    active: true,
    category: "Hamburguesas",
    sortOrder: 9,
    name: "Chicken Sandwich",
    description: "Chicken patty, provolone cheese, mayo, lettuce, tomato.",
    price: null,
    includesFries: true,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "taco-fish",
    active: true,
    category: "Tacos",
    sortOrder: 1,
    name: "Fish",
    description: "Tilapia fish, chipotle mayo, lettuce, pico de gallo.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "taco-crispy",
    active: true,
    category: "Tacos",
    sortOrder: 2,
    name: "Crispy",
    description: "Ground beef or chicken, cheese, lettuce, pico de gallo, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "taco-burrito",
    active: true,
    category: "Tacos",
    sortOrder: 3,
    name: "Burrito",
    description: "Choice of meat, lettuce, pico de gallo, rice, beans.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "taco-quesadilla",
    active: true,
    category: "Tacos",
    sortOrder: 4,
    name: "Quesadilla",
    description: "Served with pico de gallo, lettuce, sour cream, avocado.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "taco-salad",
    active: true,
    category: "Tacos",
    sortOrder: 5,
    name: "Taco Salad",
    description: "Choice of meat, beans, lettuce, avocado, pico de gallo, cheese, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "taco-quesabirria",
    active: true,
    category: "Tacos",
    sortOrder: 6,
    name: "Quesabirria",
    description: "Order of 3 with consommé, onion, cilantro, cheese, and limes.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-enchilada",
    active: true,
    category: "Tacos",
    sortOrder: 7,
    name: "Enchilada",
    description: "Chicken or beef, melted cheese, or Mexican style.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "taco-street-tacos",
    active: true,
    category: "Tacos",
    sortOrder: 8,
    name: "Street Tacos",
    description: "Classic street tacos with choice of meat.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: true,
  },
  {
    id: "torta-sencilla",
    active: true,
    category: "Tortas",
    sortOrder: 1,
    name: "Sencilla",
    description: "Choice of meat, lettuce, mayo, tomato, avocado, beans.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "torta-jamon",
    active: true,
    category: "Tortas",
    sortOrder: 2,
    name: "Jamón",
    description: "Ham, beans, lettuce, tomato, avocado, cheese, queso fresco.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "torta-philly-steak",
    active: true,
    category: "Tortas",
    sortOrder: 3,
    name: "Philly Steak",
    description: "Tender slices of meat, sautéed peppers and onions, melted provolone cheese.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "torta-cubana",
    active: true,
    category: "Tortas",
    sortOrder: 4,
    name: "Cubana",
    description:
      "Philly steak, ham, Mexican chorizo, sausage, beans, mayo, lettuce, tomato, avocado.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "antojito-sopes",
    active: true,
    category: "Antojitos",
    sortOrder: 1,
    name: "Sopes",
    description: "Beans, choice of meat, lettuce, queso fresco, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "antojito-gorditas",
    active: true,
    category: "Antojitos",
    sortOrder: 2,
    name: "Gorditas",
    description: "Beans, choice of meat, lettuce, queso fresco, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "antojito-huaraches",
    active: true,
    category: "Antojitos",
    sortOrder: 3,
    name: "Huaraches",
    description: "Beans, choice of meat, lettuce, queso fresco, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "antojito-flautas",
    active: true,
    category: "Antojitos",
    sortOrder: 4,
    name: "Flautas",
    description:
      "Chicken or beef, lettuce, pico de gallo, avocado, queso fresco, sour cream, rice and beans.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "antojito-pambazos",
    active: true,
    category: "Antojitos",
    sortOrder: 5,
    name: "Pambazos",
    description: "Chorizo with potato, lettuce, queso fresco, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "antojito-quesadilla-frita",
    active: true,
    category: "Antojitos",
    sortOrder: 6,
    name: "Quesadilla Frita",
    description: "Choice of meat, lettuce, queso fresco, sour cream.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "antojito-nachos",
    active: true,
    category: "Antojitos",
    sortOrder: 7,
    name: "Nachos",
    description: "Choice of meat, beans, cheese, pico de gallo, sour cream, jalapeños.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: false,
  },
  {
    id: "antojito-papas-locas",
    active: true,
    category: "Antojitos",
    sortOrder: 8,
    name: "Papas Locas",
    description:
      "French fries, nacho cheese, choice of meat, pico de gallo, sour cream, avocado.",
    price: null,
    includesFries: false,
    meatChoiceRequired: true,
    featured: true,
  },
  {
    id: "kids-fingers",
    active: true,
    category: "Kids Menu",
    sortOrder: 1,
    name: "Fingers",
    description: "Kids chicken fingers.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "kids-side-fries",
    active: true,
    category: "Kids Menu",
    sortOrder: 2,
    name: "Side Fries",
    description: "Side order of fries.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "kids-cheese-quesadilla",
    active: true,
    category: "Kids Menu",
    sortOrder: 3,
    name: "Cheese Quesadilla",
    description: "Kids cheese quesadilla.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-coke",
    active: true,
    category: "Drinks",
    sortOrder: 1,
    name: "Coke",
    description: "Coca-Cola drink.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-jarritos",
    active: true,
    category: "Drinks",
    sortOrder: 2,
    name: "Jarritos",
    description: "Mexican soda.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-aguas-frescas",
    active: true,
    category: "Drinks",
    sortOrder: 3,
    name: "Aguas Frescas",
    description: "Fresh flavored aguas frescas.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
];
