import type { LocationItem } from "./schema";

export const localLocationItems: LocationItem[] = [
  {
    id: "restaurant-southwest-blvd",
    active: true,
    type: "restaurant",
    sortOrder: 0,
    name: "La Hamburguesa Loca",
    label: "Restaurant Location",
    address: "904 Southwest Blvd",
    city: "Kansas City",
    state: "MO",
    zip: "64108",
    hours: "Open 5:00 PM - 11:00 PM",
    phone: "(816) 589-8925",
    email: "lahamburguesaloca@yahoo.com",
    status: "Open",
    statusNote: "Permanent restaurant location",
    mapsUrl: "",
    embedUrl: "",
    lat: null,
    lng: null,
    lastUpdated: "",
  },
  {
    id: "food-truck-independence-ave",
    active: true,
    type: "food_truck",
    sortOrder: 1,
    name: "La Hamburguesa Loca Food Truck",
    label: "Food Truck Location",
    address: "3009 Independence Ave",
    city: "Kansas City",
    state: "MO",
    zip: "64124",
    hours: "Open 5:00 PM - 11:00 PM",
    phone: "(816) 589-8925",
    email: "lahamburguesaloca@yahoo.com",
    status: "Open",
    statusNote: "At Al Halal Grocery Store",
    mapsUrl: "",
    embedUrl: "",
    lat: null,
    lng: null,
    lastUpdated: "",
  },
];
